name: Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/unit/**'
      - 'package*.json'
      - 'tsconfig.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/unit/**'
      - 'package*.json'
      - 'tsconfig.json'

jobs:
  test-unit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run unit tests only
      run: npm run test:unit